### ISSUE TITLE
restrict() is inconsistent in the size of empty matrices it returns for ts objects

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/vandermeerlab#34]
sample output from the [plotting workflow](https://github.com/mvdm/vandermeerlab/blob/master/code-matlab/example_workflows/WORKFLOW_PlotOrderedRaster.m):

```
>> expCond(1).S.t

 Columns 24 through 28

    [6.2494e+03]    [60x1 double]    [0x1 double]    []    [2x1 double]
```

note `[0x1]` and `[]`!

**Comment by youkitan** [comment]
without knowing this issue existed, I had found the same problem in restrict2 and actually made a commit "fixing" this issue in the same way you had. So restrict no longer does this (see commit 15f1cddee67a64211d93d2c4186b84bc55b1b94f)
