### ISSUE TITLE
Bug in CoOccurQ()

### ISSUE THREAD

**Issue by emirvine** [vandermeerlab/vandermeerlab#49]
When converting the q matrix to an activity matrix (boolean of whether that neuron is active in a given bin), should be >= minimum_spike value.

line 56, Q(Q > 1) = 1;
should be Q(Q >= 1) = 1; (or Q(Q >= myminimum) = 1;

**Comment by mvdm** [comment]
Under what circumstances would the output of doing Q(Q > 1) = 1 and Q(Q >= 1) = 1 be different?

**Comment by emirvine** [comment]
Right, I guess here the output is the same because Q values equal to 1 are kept unchanged in the matrix. An explanation would have helped. I assumed that a new Q matrix was being created, but your code modifies the existing Q. In Python this would be an issue because you would be modifying the Q that you get passed in, but I tested this in Matlab and apparently it makes a local copy of all the arguments passed in. Personally, I think that Q(Q >= 1) = 1 is more clear and transparent for what you're doing, but it's not my code.

**Comment by mvdm** [comment]
Wait, what? Surely in Python, as in MATLAB, function arguments have local scope by default (i.e. within coOccurQ() in this case, so would not modify Q in the main workspace), unless you define it as global within the function... or am I misreading your comment?

**Comment by emirvine** [comment]
Oh, no. This has nothing to do with the scope. This is about the difference between how Matlab seems to copy arrays whereas Python will use a pointer to an object.
See http://pythontutor.com/ for a visualization of how names and values are used in Python and https://www.youtube.com/watch?v=_AEJHKGk9ns for a good PyCon talk about it.

**Comment by youkitan** [comment]
I'm interested in this discussion but I'm a bit confused about the problem. Is the problem...
a) the different function of ">" vs ">=" as an operator?
b) how the variable Q is manipulated? (i.e.., matlab vs python differences)
c) having a concise description of what is an activity matrix (e.g., boolean Q matrix)
d) all of the above
