### ISSUE TITLE
FindFieldTime() should work on ts objects

### ISSUE THREAD

**Issue by kleaman** [vandermeerlab/vandermeerlab#87]
want to be able to use this on things like events, as loaded by `LoadEvents()`

right now gives error because seems designed for some strange input that has timestamps in multiple fields??

```
>> FindFieldTime([], evt, 1756)
Operator '>' is not supported for operands of type 'cell'.

Error in FindFieldTime (line 41)
        keep_idx = find(all_times > t_in);
 ```

**Comment by kleaman** [comment]
@mvdm please fix thid

**Comment by mvdm** [comment]
I figured it would make most sense for now to create a separate function to work on `ts` objects. That way, the new function (`FindTSTime()`) can live in the `ts` datatypes folder where it's expected, and get tested along with other `ts` functions.
